"use strict";
const {test}=require("node:test");const assert=require("node:assert/strict");const fs=require("fs"),os=require("os"),path=require("path");
const {createService}=require("../lib/discussion/service");const {createSchedulingStore}=require("../lib/discussion/store");
const actor={id:"test@example.test",canApprove:true};
const source={id:"shell",plan:{applicationId:"app",candidateId:"candidate",timezone:"America/Los_Angeles",events:[{title:"Design",start:"2030-01-02T18:00:00Z",end:"2030-01-02T19:00:00Z",interviewers:[{email:"interviewer@example.test"}],room:{name:"Test room"}}],blockers:[]}};
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),"poetic-discussion-"));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let sent=0;const store=createSchedulingStore({dir});const service=createService({store,clientId:"poetic",sourceProposals:async()=>[source],candidates:async()=>[{applicationId:"app",candidateId:"candidate",candidateName:"Test",jobTitle:"FDE",status:"Active"}],candidateChannels:{candidate:{channelId:"C123"}},slack:async()=>{sent++;return {ts:"1",channel:"C123"};}});return {service,store,sent:()=>sent,dir};}
test("copying a shell proposal creates a separate discussion draft without booking approval",async t=>{const {service,sent}=fixture(t);const d=await service.importSource("shell",actor);assert.equal(d.state,"draft");assert.equal(d.bookingApproval,null);assert.equal(d.plan.sessions[0].title,"Design");assert.equal(source.state,undefined);assert.equal(sent(),0);});
test("discussion approval requires the reviewed revision and leaves original shell unchanged",async t=>{const {service,sent}=fixture(t);const d=await service.importSource("shell",actor);const shared=await service.share(d.id,{revision:1,digest:d.digest,channelId:"C123"},actor);assert.equal(shared.state,"shared");assert.equal(sent(),1);assert.equal(shared.bookingApproval,null);assert.equal(source.approval,undefined);});
test("duplicate imported draft is rejected rather than reported as saved",async t=>{const {service}=fixture(t);await service.importSource("shell",actor);await assert.rejects(service.importSource("shell",actor),{status:409});});
test("Poetic discussion uses separate storage from booking proposals",async t=>{const {service,dir}=fixture(t);await service.importSource("shell",actor);assert.equal(fs.existsSync(path.join(dir,"discussion.json")),true);assert.equal(fs.existsSync(path.join(dir,"scheduling.json")),false);});
test("Poetic discussion rejects users without approval permission",async t=>{const {service}=fixture(t);await assert.rejects(service.importSource("shell",{id:"viewer",canApprove:false}),{status:403});});
