'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {normalizeSubmission,createAvailabilitySource}=require('../src/scheduling/availability-source');
const now=Date.parse('2026-09-21T12:00:00Z'),id=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const submission=()=>({complete:true,timezone:'America/New_York',windows:[{start:'2026-09-28T13:00:00Z',end:'2026-09-28T21:00:00Z'},{start:'2026-09-29T13:00:00Z',end:'2026-09-29T21:00:00Z'}]});
test('submission windows preserve absolute time and produce local form values',()=>{const r=normalizeSubmission(submission(),now);assert.equal(r.localWindows[0].start,'2026-09-28T09:00');assert.equal(r.windows[1].end,'2026-09-29T21:00:00.000Z');});
test('incomplete or offset-free submissions cannot silently become availability',()=>{for(const delta of [{complete:false},{timezone:'bad'},{windows:[{start:'2026-09-28T09:00',end:'2026-09-28T17:00'}]}])assert.throws(()=>normalizeSubmission({...submission(),...delta},now));});
test('past submissions are counted but never reused as future availability',()=>{const d=submission();d.windows.push({start:'2026-09-19T13:00:00Z',end:'2026-09-19T21:00:00Z'});d.windows.push(d.windows[0]);const r=normalizeSubmission(d,now);assert.equal(r.expiredCount,1);assert.equal(r.windows.length,2);});
function fixture(){const schedule={id:id(2),applicationId:id(1),status:'CandidateAvailabilitySubmitted',interviewStageId:id(4),updatedAt:'2026-09-21T12:00:00Z'};const app={id:id(1),status:'Active',candidate:{id:id(3),name:'Candidate'},currentInterviewStage:{id:id(4)}};const flags={};let inspection;const source=createAvailabilitySource({key:'test',clientId:'client',now:()=>now,inspect:async input=>{inspection=input;if(flags.changed)schedule.status='Scheduled';return {...submission(),applicationId:id(1),candidateId:flags.wrongCandidate?id(99):id(3),scheduleId:id(2)};},request:async(url,opts)=>{const body=JSON.parse(opts.body);assert.equal(body.applicationId,id(1));return {ok:true,json:async()=>({success:true,results:url.endsWith('application.info')?app:[schedule]})};}});return {source,flags,app,schedule,inspection:()=>inspection};}
test('fresh request binding supplies server identities and revalidates after reading',async()=>{const f=fixture(),r=await f.source.load({applicationId:id(1),scheduleId:id(2),candidateId:id(99)});assert.equal(r.source,'ashby_submission');assert.equal(f.inspection().candidateId,id(3));assert.equal(r.bookingEnabled,false);});
test('wrong candidate, changed request, archived application and old stage fail closed',async()=>{for(const mutation of [f=>f.flags.wrongCandidate=true,f=>f.flags.changed=true,f=>f.app.status='Archived',f=>f.schedule.interviewStageId=id(99)]){const f=fixture();mutation(f);await assert.rejects(()=>f.source.load({applicationId:id(1),scheduleId:id(2)}));}});
