'use strict';
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {createBookingEngine,receiptMatches}=require('../src/scheduling/booking-engine');
const {createBookingStore}=require('../src/scheduling/booking-store');
const now=Date.parse('2026-09-21T12:00:00Z');
const user={id:'coordinator',canApprove:true};
function plan(){return {clientId:'test',applicationId:'app',candidateId:'candidate',candidateEmail:'candidate@example.com',sourceFingerprint:'facts',templateRevision:'v1',communications:{sendCandidateInvite:true,sendInterviewerInvite:true,sendConfirmation:true,confirmation:{from:'coordinator@example.com',to:'candidate@example.com',cc:[],bcc:[],subject:'Confirmed',body:'Test interview'}},events:[{key:'welcome',interviewId:'interview',title:'Welcome',start:'2026-09-22T16:00:00Z',end:'2026-09-22T16:15:00Z',interviewers:[{userId:'mary',email:'mary@example.com'}],location:'Video',conferencing:{provider:'none'},notify:['candidate@example.com','mary@example.com']}]};}
function receipt(p){return {confirmation:{state:'sent',externalId:'email',to:p.candidateEmail,contentDigest:require('../src/scheduling/service').digest(p.communications.confirmation)},scheduleId:'schedule',applicationId:p.applicationId,candidateId:p.candidateId,readBack:true,events:p.events,notifications:p.events.flatMap(e=>e.notify.map(recipient=>({eventKey:e.key,recipient,state:'sent',externalId:'notification-'+e.key+recipient})))};}
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'booking-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const store=createBookingStore(dir);let calls=0;const source={suggest:async()=>plan(),revalidate:async()=>({ready:true,available:true,sourceFingerprint:'facts',templateRevision:'v1',checkedAt:now})};const executor={verified:true,submit:async()=>{calls++;return {};},readBack:async p=>receipt(p)};const deps={store,source,executor,clientId:'test',userById:async()=>user,now:()=>now};return {dir,store,source,executor,deps,engine:createBookingEngine(deps),calls:()=>calls};}
async function approved(s){const draft=await s.engine.draft({},user);return s.engine.approve(draft.id,draft,user);}
test('requires a distinct approval and executes at most once with concurrent requests',async t=>{const s=setup(t);const draft=await s.engine.draft({},user);assert.deepEqual(await s.engine.execute(draft.id),{skipped:true});assert.equal(s.calls(),0);await s.engine.approve(draft.id,draft,user);await Promise.all([s.engine.execute(draft.id),s.engine.execute(draft.id)]);assert.equal(s.calls(),1);assert.equal((await s.store.get(draft.id)).state,'scheduled');assert.equal((await createBookingStore(s.dir).get(draft.id)).state,'scheduled');});
test('an uncertain write persists and cannot be retried after restart',async t=>{const s=setup(t);s.executor.readBack=async()=>{throw Error('timeout');};const row=await approved(s);await s.engine.execute(row.id);const restarted=createBookingEngine({...s.deps,store:createBookingStore(s.dir)});assert.deepEqual(await restarted.execute(row.id),{skipped:true});assert.equal(s.calls(),1);assert.equal((await s.store.get(row.id)).state,'reconciliation_required');await assert.rejects(()=>s.engine.draft({},user),/unresolved/);});
test('revoked coordinator permission prevents submission',async t=>{const s=setup(t);const row=await approved(s);const engine=createBookingEngine({...s.deps,userById:async()=>({...user,canApprove:false})});await engine.execute(row.id);assert.equal(s.calls(),0);assert.equal((await s.store.get(row.id)).state,'needs_review');});
test('stale or changed availability prevents submission',async t=>{const s=setup(t);const row=await approved(s);s.source.revalidate=async()=>({ready:true,available:true,sourceFingerprint:'facts',templateRevision:'v1',checkedAt:now-61000});await s.engine.execute(row.id);assert.equal(s.calls(),0);assert.equal((await s.store.get(row.id)).state,'needs_review');});
test('unverified adapter and stale draft cannot receive approval',async t=>{const s=setup(t);const row=await s.engine.draft({},user);s.executor.verified=false;await assert.rejects(()=>s.engine.approve(row.id,row,user),/not been verified/);s.executor.verified=true;await assert.rejects(()=>s.engine.approve(row.id,{...row,revision:99},user),/latest/);assert.equal(s.calls(),0);});
test('source cannot draft for another client',async t=>{const s=setup(t);s.source.suggest=async()=>({...plan(),clientId:'other'});await assert.rejects(()=>s.engine.draft({},user),/Wrong client/);});
test('readback requires confirmed delivery of every event to every recipient',()=>{const p=plan();const r=receipt(p);assert.equal(receiptMatches(p,r),true);assert.equal(receiptMatches(p,{...r,events:undefined}),false);assert.equal(receiptMatches(p,{...r,notifications:r.notifications.slice(1)}),false);assert.equal(receiptMatches(p,{...r,notifications:r.notifications.map(n=>({...n,state:'queued'}))}),false);const two={...p,events:[...p.events,{...p.events[0],key:'second'}]};assert.equal(receiptMatches(two,{...r,events:two.events}),false);});
test('uncertain booking blocks execution for another candidate',async t=>{const s=setup(t);const a=await approved(s);s.source.suggest=async()=>({...plan(),candidateId:'second'});const b=await approved(s);s.executor.readBack=async()=>null;await s.engine.execute(a.id);assert.deepEqual(await s.engine.execute(b.id),{skipped:true});assert.equal(s.calls(),1);});
test('calendar delivery without the requested confirmation cannot count as success',()=>{const p=plan();p.communications={sendConfirmation:true,confirmation:{to:p.candidateEmail,subject:'Test',body:'Confirmed'}};assert.equal(receiptMatches(p,{...receipt(p),confirmation:undefined}),false);const {digest}=require('../src/scheduling/service');const r={...receipt(p),confirmation:{state:'sent',externalId:'email',to:p.candidateEmail,contentDigest:digest(p.communications.confirmation)}};assert.equal(receiptMatches(p,r),true);assert.equal(receiptMatches(p,{...r,confirmation:{...r.confirmation,to:'wrong@example.com'}}),false);});
test('rejected drafts cannot be approved or sent',async t=>{const s=setup(t);const row=await s.engine.draft({},user);const rejected=await s.engine.reject(row.id,row,user);await assert.rejects(()=>s.engine.approve(row.id,rejected,user),/not awaiting/);assert.deepEqual(await s.engine.execute(row.id),{skipped:true});assert.equal(s.calls(),0);});
