'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),express=require('express');
const {bookingRoutes}=require('../src/scheduling/booking-routes');
async function fixture(t){let approvals=0,executions=0;const app=express();app.use(express.json());app.use((req,res,next)=>{if(req.get('X-Test-User')==='coordinator')req.schedulingUser={id:'coordinator',canApprove:true};next();});app.use('/booking',bookingRoutes({clientId:'a',facts:{load:async input=>({applicationId:input.applicationId,availabilityVerified:false})},inspectDraft:async payload=>payload,inspectCalendar:async payload=>payload,store:{list:async()=>[{id:'a',clientId:'a'},{id:'b',clientId:'b'}],get:async()=>({state:'scheduled'})},engine:{draft:async()=>({state:'draft'}),approve:async()=>{approvals++;return{id:'a'};},execute:async()=>{executions++;},reject:async()=>({state:'rejected'})}}));const server=await new Promise(resolve=>{const server=app.listen(0,'127.0.0.1',()=>resolve(server));});t.after(()=>new Promise(resolve=>server.close(resolve)));return {url:`http://127.0.0.1:${server.address().port}/booking`,counts:()=>({approvals,executions})};}
const headers={'X-Test-User':'coordinator','X-Scheduling-Request':'1','Content-Type':'application/json'};
test('booking data requires coordinator authentication and remains client scoped',async t=>{const f=await fixture(t);assert.equal((await fetch(f.url)).status,403);const r=await fetch(f.url,{headers});assert.deepEqual((await r.json()).drafts,[{id:'a',clientId:'a'}]);});
test('cross-site approval cannot dispatch an invitation',async t=>{const f=await fixture(t);const r=await fetch(f.url+'/a/approve',{method:'POST',headers:{...headers,Origin:'https://evil.example'},body:'{}'});assert.equal(r.status,403);assert.deepEqual(f.counts(),{approvals:0,executions:0});});
test('drafting never dispatches; explicit approval dispatches once',async t=>{const f=await fixture(t);await fetch(f.url+'/drafts',{method:'POST',headers,body:'{}'});assert.deepEqual(f.counts(),{approvals:0,executions:0});const r=await fetch(f.url+'/a/approve',{method:'POST',headers,body:'{}'});assert.equal(r.status,200);assert.deepEqual(f.counts(),{approvals:1,executions:1});});

test('details lookup is coordinator-only and never dispatches',async t=>{const f=await fixture(t);assert.equal((await fetch(f.url+'/details',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);const r=await fetch(f.url+'/details',{method:'POST',headers,body:JSON.stringify({applicationId:'test'})});assert.deepEqual(await r.json(),{applicationId:'test',availabilityVerified:false});assert.deepEqual(f.counts(),{approvals:0,executions:0});});

test('draft inspection ignores client-supplied candidate identity',async t=>{const f=await fixture(t);const r=await fetch(f.url+'/inspect-draft',{method:'POST',headers,body:JSON.stringify({applicationId:'test',candidateId:'spoofed',candidateName:'spoofed',draftId:'draft'})});assert.equal(r.status,200);assert.deepEqual(await r.json(),{draftId:'draft',applicationId:'test'});assert.deepEqual(f.counts(),{approvals:0,executions:0});});

test('calendar inspection authenticates and ignores client-supplied interviewer identity',async t=>{const f=await fixture(t);const body=JSON.stringify({applicationId:'test',candidateId:'spoofed',interviewer:{name:'spoofed',email:'spoofed@example.com'},draftId:'draft'});assert.equal((await fetch(f.url+'/inspect-calendar',{method:'POST',headers:{'Content-Type':'application/json'},body})).status,403);const r=await fetch(f.url+'/inspect-calendar',{method:'POST',headers,body});assert.equal(r.status,200);assert.deepEqual(await r.json(),{draftId:'draft',applicationId:'test'});assert.deepEqual(f.counts(),{approvals:0,executions:0});});
