"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync(require.resolve('../src/auth'),'utf8');
function auth(){const module={exports:{}};vm.runInNewContext(source,{module,Buffer,require:name=>name==='./config'?{schedulingApprovers:[{username:'Test Scheduler',password:'fictional-individual-secret'}],dashboardUser:'shared',dashboardPassword:'fictional-shared-secret'}:require(name)});return module.exports.basicAuth;}
const basic=(u,p)=>'Basic '+Buffer.from(u+':'+p).toString('base64');
function request(overrides={}){const req={method:'POST',path:'/api/ashby-connection/status',headers:{authorization:basic('shared','fictional-shared-secret'),'x-coordinator-authorization':basic('Test Scheduler','fictional-individual-secret')},...overrides};const res={headers:{},code:200,set(k,v){this.headers[k]=v;return this;},status(c){this.code=c;return this;},json(d){this.data=d;return this;},send(d){this.data=d;return this;}};let next=false;auth()(req,res,()=>{next=true;});return {req,res,next};}
test('explicit coordinator identity works alongside cached shared dashboard login',()=>{const r=request();assert.equal(r.next,true);assert.equal(r.req.schedulingUser.id,'Test Scheduler');assert.equal(r.req.schedulingUser.canApprove,true);assert.equal(r.res.headers['Cache-Control'],'no-store');});
test('bad explicit credentials cannot fall back to a shared or cached approver account',()=>{const r=request({headers:{authorization:basic('Test Scheduler','fictional-individual-secret'),'x-coordinator-authorization':basic('Test Scheduler','wrong')}});assert.equal(r.next,false);assert.equal(r.res.code,403);assert.equal(r.req.schedulingUser,undefined);assert.equal(r.res.headers['WWW-Authenticate'],undefined);});
test('connection credentials cannot elevate other dashboard endpoints',()=>{const r=request({path:'/api/scheduling-review/drafts'});assert.equal(r.next,true);assert.equal(r.req.schedulingUser,undefined);});
test('shared credentials cannot be used as an explicit coordinator login',()=>{const r=request({headers:{'x-coordinator-authorization':basic('shared','fictional-shared-secret')}});assert.equal(r.res.code,403);assert.equal(r.next,false);});
test('coordinator login explicitly authenticates booking reads and approvals',()=>{for(const [method,path] of [['GET','/api/scheduling-booking'],['POST','/api/scheduling-booking/draft/approve']]){const r=request({method,path});assert.equal(r.next,true);assert.equal(r.req.schedulingUser.id,'Test Scheduler');}});
test('bad booking credentials never fall back to shared dashboard login',()=>{const r=request({path:'/api/scheduling-booking/drafts',headers:{authorization:basic('shared','fictional-shared-secret'),'x-coordinator-authorization':basic('Test Scheduler','wrong')}});assert.equal(r.next,false);assert.equal(r.res.code,403);});
