'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict');
const {proposeCalendarSchedule}=require('../src/scheduling/full-calendar-schedule');
const now=Date.parse('2026-09-21T00:00Z'),interval={start:'2026-09-28T13:00:00Z',end:'2026-09-28T21:00:00Z'};
const a={userId:'a',name:'A'},b={userId:'b',name:'B'};
function input(){
 const sessions=[{sessionId:'one',title:'Flexible',interviewId:'1',durationMinutes:60,assignmentVerified:true,requiredCount:1,eligibleInterviewers:[a,b]},{sessionId:'two',title:'Fixed',interviewId:'2',durationMinutes:30,assignmentVerified:true,requiredCount:1,eligibleInterviewers:[a]}];
 return {sessions,windows:[{start:'2026-09-28T09:00',end:'2026-09-28T17:00'}],timezone:'America/New_York',now,calendars:[a,b].map(p=>({userId:p.userId,verified:true,coverageVerified:true,workingHoursVerified:true,checkedAt:now,coverage:[interval],busy:[],sessionWorkingWindows:{one:[interval],two:[interval]},limits:{dailyLimit:null,weeklyLimit:null}}))};
}
test('full schedule uses free alternative, preserves fixed assignment and waits for all calendars',()=>{const i=input();i.calendars[0].busy=[{start:'2026-09-28T13:00Z',end:'2026-09-28T14:00Z'}];const r=proposeCalendarSchedule(i);assert.equal(r.proposals[0].events[0].interviewer.userId,'b');assert.equal(r.proposals[0].events[1].interviewer.userId,'a');assert.equal(r.availabilityVerified,true);assert.equal(r.bookingEnabled,false);});
test('missing, stale, partial or unverified calendar never counts as free',()=>{for(const change of [i=>i.calendars.pop(),i=>i.calendars[1].checkedAt-=60001,i=>i.calendars[1].coverage=[],i=>i.calendars[1].verified=false,i=>i.calendars[1].workingHoursVerified=false,i=>delete i.calendars[1].sessionWorkingWindows.one]){const i=input();change(i);assert.throws(()=>proposeCalendarSchedule(i));}});
test('busy fixed interviewer shifts the entire agenda',()=>{const i=input();i.calendars[0].busy=[{start:interval.start,end:'2026-09-28T15:00Z'}];const r=proposeCalendarSchedule(i);assert.equal(r.proposals[0].start,'2026-09-28T14:00:00.000Z');assert.equal(r.proposals[0].events[1].start,'2026-09-28T15:00:00.000Z');});
test('meeting hours restrict starts even with empty busy list',()=>{const i=input();i.calendars.forEach(c=>c.sessionWorkingWindows.one=[{start:'2026-09-28T16:00Z',end:interval.end}]);assert.equal(proposeCalendarSchedule(i).proposals[0].start,'2026-09-28T16:00:00.000Z');});
test('assignment backtracks to reserve remaining capacity for fixed interview',()=>{const i=input();i.calendars[0].limits.dailyLimit=1;i.calendars[0].interviewLoad={verified:true,checkedAt:now,timezone:'America/Los_Angeles',days:{'2026-09-28':0}};const r=proposeCalendarSchedule(i);assert.equal(r.proposals[0].events[0].interviewer.userId,'b');assert.equal(r.proposals[0].events[1].interviewer.userId,'a');});
test('weekly limit includes all assignments in this agenda',()=>{const i=input();i.sessions[0].eligibleInterviewers=[a];i.calendars[0].limits.weeklyLimit=1;i.calendars[0].interviewLoad={verified:true,checkedAt:now,timezone:'America/New_York',weeks:[{start:'2026-09-28T00:00Z',end:'2026-10-05T00:00Z',count:0}]};assert.equal(proposeCalendarSchedule(i).proposals.length,0);});
test('no fit returns no complete schedule instead of partial interviews',()=>{const i=input();i.calendars[0].busy=[interval];const r=proposeCalendarSchedule(i);assert.equal(r.status,'no_calendar_fit');assert.deepEqual(r.proposals,[]);});
test('cannot treat duplicate identities or missing load as verified',()=>{const i=input();i.calendars.push(i.calendars[0]);assert.throws(()=>proposeCalendarSchedule(i));i.calendars.pop();i.calendars[0].limits.dailyLimit=1;assert.throws(()=>proposeCalendarSchedule(i));});
