'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),os=require('os'),path=require('path');
const {createGoogleCalendarConnection,FREEBUSY_SCOPE}=require('../src/scheduling/google-calendar-connection');
const {calendarTokenStore}=require('../src/scheduling/calendar-token-store');
const {createGoogleFreeBusy,parseFreeBusy}=require('../src/scheduling/google-freebusy');
const now=Date.parse('2026-09-21T00:00Z'),email='anna@example.com';
function fixture(){let saved=null,authOptions,active=true,revoked=0,identityEmail=email,scopes=['openid','email',FREEBUSY_SCOPE],clock=now;
 const store={load:()=>structuredClone(saved),save:v=>{saved=structuredClone(v);},clear:()=>{saved=null;}};
 const client={generateCodeVerifierAsync:async()=>({codeVerifier:'private-verifier',codeChallenge:'public-challenge'}),generateAuthUrl:opts=>{authOptions=opts;return 'https://accounts.google.com/o/oauth2/v2/auth?'+new URLSearchParams({...opts,scope:opts.scope.join(' ')});},getToken:async opts=>{assert.equal(opts.codeVerifier,'private-verifier');return {tokens:{id_token:'id-token',access_token:'access-token',refresh_token:'refresh-token',expiry_date:now+3600000}};},verifyIdToken:async()=>({getPayload:()=>({email:identityEmail,email_verified:true,sub:'subject',nonce:authOptions.nonce})}),getTokenInfo:async()=>({aud:'client',scopes}),revokeToken:async()=>{revoked++;},setCredentials:()=>{},on:()=>{},getAccessToken:async()=>({token:'access-token'})};
 const service=createGoogleCalendarConnection({tenantId:'luminai',clientId:'client',clientSecret:'fake-client-secret',redirectUri:'https://example.com/api/google-calendar/callback',expectedEmail:email,keyHex:'a'.repeat(64),dataDir:'/unused',ownerAllowed:async()=>active,now:()=>clock,oauthFactory:()=>client,store});
 return {service,store,client,get authOptions(){return authOptions;},get revoked(){return revoked;},set active(v){active=v;},set identityEmail(v){identityEmail=v;},set scopes(v){scopes=v;},set clock(v){clock=v;}};
}
async function flow(f){const r=await f.service.start('coordinator');return {state:new URL(r.url).searchParams.get('state'),browserToken:r.browserToken,code:'test-code'};}
test('OAuth requests only freebusy and identity, with state, PKCE, account hint and offline consent',async()=>{const f=fixture(),r=await flow(f);assert.deepEqual(f.authOptions.scope,['openid','email',FREEBUSY_SCOPE]);assert.equal(f.authOptions.include_granted_scopes,false);assert.equal(f.authOptions.code_challenge_method,'S256');assert.equal(f.authOptions.login_hint,email);assert.equal(f.authOptions.access_type,'offline');assert.match(f.authOptions.prompt,/consent/);await f.service.finish(r);assert.equal(f.service.status().connected,true);assert.equal((await f.service.access()).token,'access-token');assert.equal(JSON.stringify(f.service.status()).includes('token'),false);assert.equal(f.store.load().tokens.id_token,undefined);await assert.rejects(f.service.finish(r),/expired|another browser/);});
test('OAuth rejects another browser, expired state, revoked coordinator and wrong account',async()=>{let f=fixture(),r=await flow(f);await assert.rejects(f.service.finish({...r,browserToken:'wrong'}));assert.equal(f.service.status().connected,false);f.clock=now+600001;await assert.rejects(f.service.finish(r));f=fixture();r=await flow(f);f.active=false;await assert.rejects(f.service.finish(r));f=fixture();r=await flow(f);f.identityEmail='wrong@example.com';await assert.rejects(f.service.finish(r),/expected/);assert.equal(f.revoked,1);assert.equal(f.service.status().connected,false);});
test('partial or broader Google grants are rejected and not persisted',async()=>{for(const scopes of [['openid','email'],['openid','email',FREEBUSY_SCOPE,'https://www.googleapis.com/auth/calendar']]){const f=fixture(),r=await flow(f);f.scopes=scopes;await assert.rejects(f.service.finish(r),/only the requested/);assert.equal(f.store.load(),null);}});
test('disconnect removes local authorization and invalidates in-flight connection identity',async()=>{const f=fixture();await f.service.finish(await flow(f));const id=(await f.service.access()).connectionId;assert.equal(f.service.isCurrent(id),true);assert.deepEqual(await f.service.disconnect('coordinator'),{connected:false,revoked:true});assert.equal(f.service.isCurrent(id),false);await assert.rejects(f.service.access(),/Connect/);});
test('missing OAuth config remains explicitly unconfigured',()=>{const s=createGoogleCalendarConnection({});assert.equal(s.status().configured,false);assert.ok(s.status().missing.includes('GOOGLE_CALENDAR_CLIENT_ID'));});
test('encrypted calendar tokens are bound to tenant and OAuth app and detect tampering',()=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'calendar-vault-')),file=path.join(dir,'tokens.json');try{const v=calendarTokenStore({file,keyHex:'b'.repeat(64),binding:'tenant-a'});v.save({refresh_token:'private-test-token'});assert.equal(fs.readFileSync(file,'utf8').includes('private-test-token'),false);assert.equal(v.load().refresh_token,'private-test-token');assert.equal(fs.statSync(file).mode&0o777,0o600);assert.throws(()=>calendarTokenStore({file,keyHex:'b'.repeat(64),binding:'tenant-b'}).load());const p=JSON.parse(fs.readFileSync(file));p.tag='00'.repeat(16);fs.writeFileSync(file,JSON.stringify(p));assert.throws(()=>v.load());}finally{fs.rmSync(dir,{recursive:true,force:true});}});
const query={calendarIds:['one@example.com','two@example.com'],start:now+86400000,end:now+2*86400000,checkedAt:now};
const response=()=>({kind:'calendar#freeBusy',timeMin:new Date(query.start).toISOString(),timeMax:new Date(query.end).toISOString(),calendars:{'one@example.com':{busy:[]},'two@example.com':{busy:[{start:new Date(query.start+3600000).toISOString(),end:new Date(query.start+7200000).toISOString()}]}}});
test('empty confirmed calendars are freebusy-covered, unlike missing calendars',()=>{const r=parseFreeBusy(response(),query);assert.equal(r[0].busy.length,0);assert.equal(r[0].coverageVerified,true);const d=response();delete d.calendars['one@example.com'];assert.throws(()=>parseFreeBusy(d,query));});
test('per-calendar errors, wrong coverage and malformed intervals reject the full result',()=>{for(const change of [d=>d.calendars['one@example.com'].errors=[{reason:'notFound'}],d=>d.timeMin=new Date(query.start+1).toISOString(),d=>d.calendars['two@example.com'].busy[0].end='bad',d=>d.groups={group:{calendars:['one@example.com']}}]){const d=response();change(d);assert.throws(()=>parseFreeBusy(d,query));}});
test('Google freebusy adapter uses only the fixed read-only endpoint and rejects connection changes',async()=>{let current=true;const service=createGoogleFreeBusy({now:()=>now,connection:{access:async()=>({token:'token',connectionId:'id'}),isCurrent:()=>current},request:async(url,options)=>{assert.equal(url,'https://www.googleapis.com/calendar/v3/freeBusy');const body=JSON.parse(options.body);assert.equal(body.items.length,2);assert.equal(body.timeZone,'UTC');return {ok:true,json:async()=>response()};}});const args={calendarIds:query.calendarIds,timeMin:new Date(query.start).toISOString(),timeMax:new Date(query.end).toISOString()};assert.equal((await service.read(args)).length,2);current=false;await assert.rejects(service.read(args),/changed/);});
